# Generated by Django 3.1 on 2020-11-17 16:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, verbose_name='商品详情'),
        ),
    ]
