# Generated by Django 3.1 on 2021-05-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_detail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='goods_spu',
        ),
        migrations.AlterModelTable(
            name='goodsimage',
            table='goods_image',
        ),
        migrations.AlterModelTable(
            name='goodssku',
            table='goods_sku',
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='goods_type',
        ),
        migrations.AlterModelTable(
            name='indexgoodsbanner',
            table='index_banner',
        ),
        migrations.AlterModelTable(
            name='indexpromotionbanner',
            table='index_promotion',
        ),
        migrations.AlterModelTable(
            name='indextypegoodsbanner',
            table='index_type_goods',
        ),
    ]
