# Generated by Django 3.1 on 2021-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210425_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='transit_price',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(default='', max_length=128, verbose_name='支付编号'),
        ),
    ]
