# Generated by Django 3.1 on 2021-04-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210428_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '支付宝')], default=1, verbose_name='支付方式'),
        ),
    ]
