# Generated by Django 3.1 on 2021-05-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210428_2332'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordergoods',
            table='order_goods',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='order_info',
        ),
    ]
